defconfig: Satisfy VINTF checks
This fixes the following error:
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    Missing config CONFIG_HAVE_MOVE_PMD
    Missing config CONFIG_HAVE_MOVE_PUD
    Missing config CONFIG_USERFAULTFD
: Success
INCOMPATIBLE

Change-Id: I521952819f169979f3d604452c81fb4eeee4733d
Signed-off-by: SenX <snseiix@dev.com>