timer: Call run_posix_cpu_timers() with no args
Removed by commit f76e0cb3ce6b ("posix-cpu-timers: Remove tsk argument from run_posix_cpu_timers()").

Logs:
../kernel/time/timer.c:1838:24: error: too many arguments to function call, expected 0, have 1
 1838 |                 run_posix_cpu_timers(p);
      |                 ~~~~~~~~~~~~~~~~~~~~ ^
../include/linux/posix-timers.h:121:6: note: 'run_posix_cpu_timers' declared here
  121 | void run_posix_cpu_timers(void);
      |      ^
1 error generated.

Fixes: f76e0cb3ce6b ("posix-cpu-timers: Remove tsk argument from run_posix_cpu_timers()")
Signed-off-by: Muhammad Guntur <mochtur@gmail.com>